# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://joeat1.github.io
date_format: "ordinal"
title: 日志
subtitle: "信息搜集怪"
description: "信息搜集怪"
keywords: 信息搜集怪, 程序员
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 3
repository: joeat1/joeat1.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 组件配置
components:
    # 分享
    share:
        enabled: false
    # # 不蒜子访问统计
    # busuanzi:
    #     enabled: true
    #     start_date: 2020-05-03
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 文章字数统计
word_count:
    enabled: true
# 代码高亮风格，支持的 theme 列表见 https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: Joeat1
organization: 
organization_url: 
github_username: joeat1
location: China
email: 

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours

# https://github.com/gitalk/gitalk#install
gitalk:
    enable: true #是否开启
    githubID: joeat1 #你的Github用户名
    owner: joeat1
    adminUser: joeat1 # 评论初始化账户(GitHub ID)
    id: location.pathname
    repo: blog-comments
    clientID: 783cc6c5b794f3c1b384
    clientSecret: 9cb2b8ebb436afe54876476c24736426d38d1ab8
    distraction_free_mode: true
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10
